# PinCart AI — Azure Static Web Apps configuration
# Place this in the frontend root for Azure deployment

platform:
  apiRuntime: node:18

navigationFallback:
  rewrite: /index.html
  exclude:
    - "/_next/*"
    - "/api/*"
    - "/*.{css,js,json,ico,png,jpg,svg,woff2}"

routes:
  - route: /api/*
    allowedRoles:
      - authenticated

globalHeaders:
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-XSS-Protection: "1; mode=block"
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Referrer-Policy: strict-origin-when-cross-origin
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' https://*.pinimg.com https://*.alicdn.com data:; connect-src 'self' https://*.supabase.co https://*.sentry.io"
