# PinCart AI — DigitalOcean App Platform Spec
# Deploy: doctl apps create --spec infrastructure/digitalocean-app.yaml

name: pincart-backend
region: nyc
services:
  - name: api
    github:
      repo: thatjelvin/pincart
      branch: main
      deploy_on_push: true
    source_dir: pincart/backend
    environment_slug: python
    instance_count: 1
    instance_size_slug: professional-xs
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    health_check:
      http_path: /health
    envs:
      - key: SENTRY_DSN
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: MAILGUN_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: MAILGUN_DOMAIN
        scope: RUN_TIME

databases:
  - name: pincart-redis
    engine: REDIS
    production: false
    version: "7"
